# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import mce_filebrowser.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileBrowserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[(b'img', 'Image'), (b'doc', 'Document')], max_length=3)),
                ('uploaded_file', models.FileField(max_length=300, upload_to=mce_filebrowser.models.content_file_name, verbose_name='File / Image')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='Who does this file belong to?')),
            ],
        ),
    ]
